"""fix_fk_cascade_and_bigint

Revision ID: 06bbcd395166
Revises: 25f83ed7e986
Create Date: 2026-06-10 14:19:55.662805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06bbcd395166'
down_revision: Union[str, None] = '25f83ed7e986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jangdan_recommendation_ibfk_2', 'jangdan_recommendation', type_='foreignkey')
    op.create_foreign_key(None, 'jangdan_recommendation', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('performance_event', 'occurred_at_ms',
               existing_type=mysql.INTEGER(unsigned=True),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
    op.drop_constraint('recording_ibfk_1', 'recording', type_='foreignkey')
    op.create_foreign_key(None, 'recording', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('share_link_ibfk_1', 'share_link', type_='foreignkey')
    op.drop_constraint('share_link_ibfk_2', 'share_link', type_='foreignkey')
    op.create_foreign_key(None, 'share_link', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'share_link', 'recording', ['recording_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_link', type_='foreignkey')
    op.drop_constraint(None, 'share_link', type_='foreignkey')
    op.create_foreign_key('share_link_ibfk_2', 'share_link', 'session', ['session_id'], ['id'])
    op.create_foreign_key('share_link_ibfk_1', 'share_link', 'recording', ['recording_id'], ['id'])
    op.drop_constraint(None, 'recording', type_='foreignkey')
    op.create_foreign_key('recording_ibfk_1', 'recording', 'session', ['session_id'], ['id'])
    op.alter_column('performance_event', 'occurred_at_ms',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.INTEGER(unsigned=True),
               existing_nullable=False)
    op.drop_constraint(None, 'jangdan_recommendation', type_='foreignkey')
    op.create_foreign_key('jangdan_recommendation_ibfk_2', 'jangdan_recommendation', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###
