"""add folk_song table, session mode and folk_song_id, recording mixer columns

Revision ID: 1b981497ddf4
Revises: 06bbcd395166
Create Date: 2026-06-12 02:59:22.119911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b981497ddf4'
down_revision: Union[str, None] = '06bbcd395166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folk_song',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('instrument_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reference_events', mysql.JSON(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard'), server_default='medium', nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recording', sa.Column('instrument_id', sa.VARCHAR(length=64), nullable=True))
    op.add_column('recording', sa.Column('volume', mysql.FLOAT(), server_default='1.0', nullable=False))
    op.add_column('recording', sa.Column('is_muted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('recording', sa.Column('track_order', mysql.INTEGER(unsigned=True), server_default='0', nullable=False))
    op.create_foreign_key(None, 'recording', 'instrument', ['instrument_id'], ['id'], ondelete='SET NULL')
    op.add_column('session', sa.Column('mode', sa.Enum('creative', 'practice'), server_default='creative', nullable=False))
    op.add_column('session', sa.Column('folk_song_id', sa.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(None, 'session', 'folk_song', ['folk_song_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'folk_song_id')
    op.drop_column('session', 'mode')
    op.drop_constraint(None, 'recording', type_='foreignkey')
    op.drop_column('recording', 'track_order')
    op.drop_column('recording', 'is_muted')
    op.drop_column('recording', 'volume')
    op.drop_column('recording', 'instrument_id')
    op.drop_table('folk_song')
    # ### end Alembic commands ###
