"""init

Revision ID: 25f83ed7e986
Revises: 
Create Date: 2026-06-10 11:11:25.591154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25f83ed7e986'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_reference_manifest',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), nullable=False),
    sa.Column('usage_scope', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at_ms', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.Enum('gayageum', 'janggu', 'daegeum'), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('note_unit_count', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jangdan_preset',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('min_bpm', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('max_bpm', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('density_range', sa.Enum('low', 'medium', 'high', 'any'), nullable=False),
    sa.Column('meter', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_reference',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('manifest_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reference_layer', sa.Enum('analysis', 'validation', 'ux'), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=128), nullable=False),
    sa.Column('dataset_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('license_note', sa.TEXT(), nullable=False),
    sa.Column('usage_note', sa.TEXT(), nullable=False),
    sa.Column('extracted_features', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['data_reference_manifest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_unit',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('instrument_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('unit_index', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('label', sa.VARCHAR(length=16), nullable=False),
    sa.Column('base_note_name', sa.VARCHAR(length=16), nullable=True),
    sa.Column('base_pitch_cents', sa.INTEGER(), nullable=True),
    sa.Column('has_pitch_bend', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'unit_index', name='uq_instrument_unit')
    )
    op.create_table('jangdan_pattern_event',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('jangdan_preset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('step_index', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('offset_ms', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('percussion_slot', sa.VARCHAR(length=32), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['jangdan_preset_id'], ['jangdan_preset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_preset', 'jangdan_pattern_event', ['jangdan_preset_id'], unique=False)
    op.create_table('sample_asset_manifest',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), nullable=False),
    sa.Column('instrument_id', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_asset',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('manifest_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('source_layer', sa.Enum('public_asset', 'own_asset'), nullable=False),
    sa.Column('file_uri', sa.VARCHAR(length=512), nullable=False),
    sa.Column('license', sa.VARCHAR(length=128), nullable=False),
    sa.Column('attribution', sa.TEXT(), nullable=True),
    sa.Column('base_note_name', sa.VARCHAR(length=16), nullable=False),
    sa.Column('base_pitch_cents', sa.INTEGER(), nullable=False),
    sa.Column('envelope', mysql.JSON(), nullable=False),
    sa.Column('quality_flags', mysql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['sample_asset_manifest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('instrument_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sample_asset_manifest_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('schema_version', sa.VARCHAR(length=32), server_default='2026.06.mvp', nullable=False),
    sa.Column('duration_ms', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('replay_settings', mysql.JSON(), nullable=True),
    sa.Column('created_at_ms', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('updated_at_ms', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['sample_asset_manifest_id'], ['sample_asset_manifest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_created', 'session', ['created_at_ms'], unique=False)
    op.create_index('idx_session_user', 'session', ['user_id'], unique=False)
    op.create_table('instrument_unit_sample_map',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('instrument_unit_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sample_asset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('articulation', sa.VARCHAR(length=64), server_default='pluck', nullable=False),
    sa.Column('priority', mysql.TINYINT(unsigned=True), server_default='1', nullable=False),
    sa.Column('is_fallback', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['instrument_unit_id'], ['instrument_unit.id'], ),
    sa.ForeignKeyConstraint(['sample_asset_id'], ['sample_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jangdan_preset_asset',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('jangdan_preset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sample_asset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('percussion_slot', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['jangdan_preset_id'], ['jangdan_preset.id'], ),
    sa.ForeignKeyConstraint(['sample_asset_id'], ['sample_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jangdan_recommendation',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('jangdan_preset_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('estimated_bpm', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('beat_stability', sa.Float(), nullable=False),
    sa.Column('decision_status', sa.Enum('proposed', 'previewed', 'accepted', 'rejected'), server_default='proposed', nullable=False),
    sa.Column('reason', mysql.JSON(), nullable=False),
    sa.Column('created_at_ms', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('accepted_at_ms', mysql.BIGINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['jangdan_preset_id'], ['jangdan_preset.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_session', 'jangdan_recommendation', ['session_id'], unique=False)
    op.create_table('performance_event',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('occurred_at_ms', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('event_type', sa.Enum('string_pluck', 'string_bend', 'string_mute', 'glissando_step', 'string_release'), nullable=False),
    sa.Column('unit_index', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('pitch_bend_cents', mysql.SMALLINT(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('payload', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_session', 'performance_event', ['session_id'], unique=False)
    op.create_index('idx_event_time', 'performance_event', ['session_id', 'occurred_at_ms'], unique=False)
    op.create_table('recording',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file_uri', sa.VARCHAR(length=512), nullable=False),
    sa.Column('format', sa.VARCHAR(length=16), server_default='aac', nullable=False),
    sa.Column('duration_ms', mysql.INTEGER(unsigned=True), server_default='0', nullable=False),
    sa.Column('render_status', sa.Enum('pending', 'done', 'failed'), server_default='pending', nullable=False),
    sa.Column('created_at_ms', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recording_session', 'recording', ['session_id'], unique=False)
    op.create_table('share_link',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('recording_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private'), server_default='public', nullable=False),
    sa.Column('created_at_ms', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('expires_at_ms', mysql.BIGINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_link')
    op.drop_index('idx_recording_session', table_name='recording')
    op.drop_table('recording')
    op.drop_index('idx_event_time', table_name='performance_event')
    op.drop_index('idx_event_session', table_name='performance_event')
    op.drop_table('performance_event')
    op.drop_index('idx_recommendation_session', table_name='jangdan_recommendation')
    op.drop_table('jangdan_recommendation')
    op.drop_table('jangdan_preset_asset')
    op.drop_table('instrument_unit_sample_map')
    op.drop_index('idx_session_user', table_name='session')
    op.drop_index('idx_session_created', table_name='session')
    op.drop_table('session')
    op.drop_table('sample_asset')
    op.drop_table('sample_asset_manifest')
    op.drop_index('idx_pattern_preset', table_name='jangdan_pattern_event')
    op.drop_table('jangdan_pattern_event')
    op.drop_table('instrument_unit')
    op.drop_table('data_reference')
    op.drop_table('jangdan_preset')
    op.drop_table('instrument')
    op.drop_table('data_reference_manifest')
    # ### end Alembic commands ###
